# Generated by Django 3.2.4 on 2021-06-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=20, null=True)),
                ('desc', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
